---
# defaults file for icinga2-nrpe-agent

nrpe_agent_RedHat:
 - { package: "nrpe" }
 - { package: "nagios-plugins-all" }

nrpe_agent_Debian:
 - { package: "nagios-nrpe-server" }
 - { package: "nagios-nrpe-plugin" }
 - { package: "nagios-plugins" }

nrpe_agent_Gentoo:
 - { package: "nrpe" }
 - { package: "nagios-plugins" }

nrpe_agent_config: "/etc/nagios/nrpe.cfg"

# A list of allowed hosts for Nrpe agent
nrpe_allowed_hosts: "127.0.0.1,192.168.0.1"

# Plugins path for RH and other x86_64
nrpe_agent_plugins_x86_64: "/usr/lib64/nagios/plugins"

nrpe_agent_check_mem: "https://raw.githubusercontent.com/zwindler/check_mem_ng/master/check_mem_ng.sh"

# Sample NRPE check commands
nrpe_check_commands:
  check_load:
    check_load: "-w 15,10,5 -c 30,25,20"
  check_disk:
    check_disk: "-w 20% -c 10% -p /"
